### ISSUE TITLE
No local packages or working download links found for pbr>=2.0.0

### ISSUE THREAD

**Issue by eprilx** [alvaroaleman/docker-openstack-horizon#1]
Hello, I got this error when run `docker build -t horizon_image .`
Thanks for any help!

```
Processing /opt/horizon
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pbr' (maybe misspelled?)
    No local packages or working download links found for pbr>=2.0.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tU8zkJ-build/setup.py", line 29, in <module>
        pbr=True)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=2.0.0')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-tU8zkJ-build/
The command '/bin/sh -c apt update &&   apt install -y     apache2 libapache2-mod-wsgi     python-pip python-dev git &&   git clone --branch $VERSION --depth 1 https://github.com/openstack/horizon.git ${HORIZON_BASEDIR} &&   cd ${HORIZON_BASEDIR} &&   pip install . &&   pip install python-memcached &&   cp openstack_dashboard/local/local_settings.py.example openstack_dashboard/local/local_settings.py &&   sed -i 's/^DEBUG.*/DEBUG = False/g' $HORIZON_BASEDIR/openstack_dashboard/local/local_settings.py &&   echo 'COMPRESS_OFFLINE = True' >> $HORIZON_BASEDIR/openstack_dashboard/local/local_settings.py &&   sed -i 's/^OPENSTACK_KEYSTONE_URL.*/OPENSTACK_KEYSTONE_URL = os\.environ\["KEYSTONE_URL"\]/g'     $HORIZON_BASEDIR/openstack_dashboard/local/local_settings.py &&   printf  "\nALLOWED_HOSTS = ['*', ]\n" >> $HORIZON_BASEDIR/openstack_dashboard/local/local_settings.py &&   echo 'OPENSTACK_API_VERSIONS = {"identity": os.environ.get("IDENTITY_API_VERSION", 3) }'     >> $HORIZON_BASEDIR/openstack_dashboard/local/local_settings.py &&   ./manage.py collectstatic --noinput &&   ./manage.py compress --force &&   ./manage.py make_web_conf --wsgi &&   rm -rf /etc/apache2/sites-enabled/* &&   ./manage.py make_web_conf --apache > /etc/apache2/sites-enabled/horizon.conf &&   sed -i 's/<VirtualHost \*.*/<VirtualHost _default_:80>/g' /etc/apache2/sites-enabled/horizon.conf &&   chown -R www-data:www-data ${HORIZON_BASEDIR} &&   python -m compileall $HORIZON_BASEDIR &&   sed -i '/ErrorLog/c\    ErrorLog \/dev\/stderr' /etc/apache2/sites-enabled/horizon.conf &&   sed -i '/CustomLog/c\    CustomLog \/dev\/stdout combined' /etc/apache2/sites-enabled/horizon.conf &&   sed -i '/ErrorLog/c\    ErrorLog \/dev\/stderr' /etc/apache2/apache2.conf &&   apt remove -y python-dev git &&   apt autoremove -y' returned a non-zero code: 1
```

**Comment by eprilx** [comment]
Solved! Here is my change to make it work: https://github.com/eprilx/docker-openstack-horizon
